### ISSUE TITLE
_version for tsdate prior files is "undefined"

### ISSUE THREAD

**Issue by hyanwong** [awohns/tsdate#115]
I can't seem to get the current code to pick up on the tsdate version. At the moment the tray except block at the top is catching this:

```
  File "tsdate/tsdate/date.py", line 46, in <module>
    from . import _version
ImportError: cannot import name '_version' from 'tsdate' (tsdate/tsdate/__init__.py)
```

And therefore defaulting to "untitled", so my prior files are, e.g. `prior_1000df_undefined.txt`

**Comment by awohns** [comment]
I’ll add the _version.py file

**Comment by awohns** [comment]
Hmm this is a bit confusing, there's an issue here with getting the version in the packaged version of tsdate vs. the dev. version. I think using the packaged version you should be able to import the version of the software, but the dev version doesn't have _version.py because setuptools hasn't been run

**Comment by awohns** [comment]
I think it should be ok in the packaged version, but Jerome alluded to something in msprime that lets us grab the version from the dev version too.

**Comment by hyanwong** [comment]
Yes, I think we should also get it to work when installed e.g. from github (does that run setuptools?). Could you ask Jerome today perhaps?
