### ISSUE TITLE
Should g_i values be stored per edge or per node?

### ISSUE THREAD

**Issue by hyanwong** [awohns/tsdate#92]
On line https://github.com/awohns/tsdate/blob/20b9ea68e4a20b9f74c7ac9b00a64578fd8e9595/tsdate/date.py#L1366

you assign straight into `g_i[edge.child]`, but we may hit many edges with the same child, I think. Should this be `g_i[edge.child] += vv`

**Comment by awohns** [comment]
Funny you mention this, I spotted it early in my 9 hour flight and spent the next few hours trying to reconcile gil’s version of the outside with the earlier version. 

g_i should be defined for each edge, rather than each edge.child. Furthermore, there should be a G_i (big G) which collects the g_i values for each edge parent. Then, rather than divide the Inside value of the parent by the g_i of the child, we divide the G_i of the parent at time t by the g_i of the edge at time t’. This requires a new function to get the diagonal of the matrix (in addition to the upper tri).

I haven’t yet convinced myself this works, but Gil isn’t wrong often. It might be equivalent to what we did before in the case of a binary tree...

I’ll follow up with the equations which will make this clearer

**Comment by awohns** [comment]
![image](https://user-images.githubusercontent.com/10664424/73989438-a8ad8c00-493d-11ea-8399-2521a9c8b674.png)

**Comment by hyanwong** [comment]
To bring up with Gil on Monday. At the moment we store per edge, which has high memory complexity. It would be nice to be able to store a G_i per node (upwards), but I have a feeling that the equations don't work out.

**Comment by awohns** [comment]
We discussed this with Gil. Right now the default is to recalculate the G_is for memory complexity issues (storing them is hugely expensive). Gil said there isn't an easy alternative to storing or recalculating them.
